#!/usr/bin/env bash
# Configure your domain zone

if [ "$#" -eq 1 ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")

    for sub_domain in "${subdomains[@]}"; do
        record_type=$(dig "$sub_domain.$1" +short)
        
        if [ -n "$record_type" ]; then
            echo "The subdomain $sub_domain is a $record_type record and points to $1"
        fi
    done

elif [ "$#" -eq 2 ]; then
    record_type=$(dig "$2.$1" +short)
    
    if [ -n "$record_type" ]; then
        echo "The subdomain $2 is a $record_type record and points to $1"
    else
        echo "No record found for $2.$1"
    fi
fi
