#!/usr/bin/env bash
# Installs and configures HAproxy on a server

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 58027-web-01 54.237.103.36:80 check\n\tserver 58027-web-02 18.204.11.153:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
