#!/usr/bin/env bash
# A Bash script that stops 4-to_infinity_and_beyond process

pids=$( ps eaux | pgrep ./4-to_infinity_and_beyond )
counter=0

for pid in $pids; do
	if [ $counter -gt 0 ]; then
		kill -n 9 "$pid"
	fi
	counter=$((counter + 1))
done
