#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and:
# 1. displays 4 and then bad luck from China for the 4th loop iteration
# 2. displays 9 and then bad luck from Japan for the 9th loop iteration
# 3. displays 17 and then bad luck from Italy for the 17th loop iteration

COUNTER=1

while [ $COUNTER -le 20 ]; do
    case $COUNTER in
        4)
            echo "4"
            echo "bad luck from China"
            ;;
        9)
            echo "9"
            echo "bad luck from Japan"
            ;;
        17)
            echo "17"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$COUNTER"
            ;;
    esac
    COUNTER=$((COUNTER + 1))
done