#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
# 1. display hours from 0 to 12
# 2. display minutes from 1 to 59


HOUR=0

while [ $HOUR -le 12 ]; do
	echo "Hour: $HOUR"

	MIN=1

	while [ $MIN -le 59 ]; do
		echo "$MIN"
		MIN=$((MIN + 1))
	done
	HOUR=$((HOUR + 1))
done
