#!/usr/bin/env bash
# A Bash script that displays:
# 1. The content of the current directory
# 2. In a list format
# 3. Where only the part of the name after the first dash is displayed

for line in * ; do
	echo "${line#*-}"
done
