#!/usr/bin/env bash
# Runs Nginx as non-root user with nginx
sudo sed -i '1 i\user nginx;' /etc/nginx/nginx.conf
sudo sed -i "s/80 default_server/8080 default_server/g" /etc/nginx/sites-enabled/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
